//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Deck = new HashSet<Deck>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Faction { get; set; }
        public string Type { get; set; }
        public string Cost { get; set; }
        public int Loyalty { get; set; }
        public string RuleText { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
    
        public virtual ICollection<Deck> Deck { get; set; }
    }
}
