//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiagramaArcmageContainer : DbContext
    {
        public DiagramaArcmageContainer()
            : base("name=DiagramaArcmageContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Game> GameSet { get; set; }
        public DbSet<Deck> DeckSet { get; set; }
        public DbSet<Card> CardSet { get; set; }
        public DbSet<Team> TeamSet { get; set; }
        public DbSet<Tournament> TournamentSet { get; set; }
        public DbSet<Player> PlayerSet { get; set; }
        public DbSet<TeamPlayers> TeamPlayersSet { get; set; }
    }
}
