//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.StandardGame1 = new HashSet<StandardGame>();
            this.StandardGame2 = new HashSet<StandardGame>();
            this.Teams = new HashSet<Team>();
            this.StandardTournaments = new HashSet<StandardTournament>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public int Age { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<StandardGame> StandardGame1 { get; set; }
        public virtual ICollection<StandardGame> StandardGame2 { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<StandardTournament> StandardTournaments { get; set; }
    }
}
