//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardTournament : Tournament
    {
        public StandardTournament()
        {
            this.Games = new HashSet<StandardGame>();
            this.Players = new HashSet<Player>();
        }
    
    
        public virtual ICollection<StandardGame> Games { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
