//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamTournament : Tournament
    {
        public TeamTournament()
        {
            this.Games = new HashSet<TeamGame>();
            this.Teams = new HashSet<Team>();
        }
    
    
        public virtual ICollection<TeamGame> Games { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
