//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.GameAsTeam1 = new HashSet<TeamGame>();
            this.GameAsTeam2 = new HashSet<TeamGame>();
            this.Players = new HashSet<Player>();
            this.TeamTournaments = new HashSet<TeamTournament>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<TeamGame> GameAsTeam1 { get; set; }
        public virtual ICollection<TeamGame> GameAsTeam2 { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<TeamTournament> TeamTournaments { get; set; }
    }
}
